language: java
jdk:
  - openjdk7
  - oraclejdk8
script: for mod in cadc-app-kit cadc-download-manager cadc-upload-manager cadc-download-manager-server ; do cd $mod; gradle --info javadoc build install || break -1; cd ..; done

