language: java
jdk:
  - openjdk7
  - oraclejdk8
before_script: openssl s_client -CApath /etc/ssl/certs/ -connect plugins.gradle.org:443 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/gradle.crt; sudo keytool -importcert -noprompt -file /tmp/gradle.crt -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts -alias root -storepass changeit;
script: for mod in cadc-app-kit cadc-download-manager cadc-upload-manager cadc-download-manager-server ; do cd $mod; gradle --info javadoc build install || break -1; cd ..; done

