name: Java CI with Gradle

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin

    - name: build and test cadc-download-manager
      run: cd cadc-download-manager && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test cadc-download-manager-server
      run: cd cadc-download-manager-server && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test downloadManager application
      run: cd downloadManager && ../gradlew --info clean build javadoc checkstyleMain
